ClusterServerPool {
   MasterReadPriority 60
   StaticSlaveReadPriority 50
   DynamicSlaveReadPriority 50
   RefreshInterval 1
   ServerTimeout 1
   ServerFailureLimit 10
   ServerRetryTimeout 1
   KeepAlive 120
   Servers {
        + host.docker.internal:6000
        + host.docker.internal:6001
        + host.docker.internal:6002
        + host.docker.internal:6003
        + host.docker.internal:6004
        + host.docker.internal:6005
   }
}
