
name: qdrant
services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    restart: unless-stopped
    # env_file:
    #   - .env
    ports:
      - 6333:6333
      - 6334:6334
    volumes:
      - type: bind
        source: ../volumes/qdrant
        target: /qdrant/storage
      - type: bind
        source: ../scripts/certs/ca/ca.crt
        target: /qdrant/tls/ca.pem
        read_only: true
      - type: bind
        source: ../scripts/certs/qdrant/fullchain.crt
        target: /qdrant/tls/cert.pem
        read_only: true
      - type: bind
        source: ../scripts/certs/qdrant/server.key
        target: /qdrant/tls/key.pem
        read_only: true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/dashboard#/welcome"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
