
services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    expose:
      - 11434
    ports:
      - 11434:11434
    volumes:
      - ../volumes/ollama:/root/.ollama
