#!/usr/bin/env bash
############################################################
# Created by: Guy Shaked                                   #
# Github: https://github.com/shakedguy                     #
# Phone: +972542422521                                     #
############################################################


# Generate server private key, certificate signing request (CSR) and self-signed certificate using openssl.cnf configuration file.
# and sign it with the CA certificate.
# Usage: ./gen-server-cert [output_directory] -name [server_name] -ca_key [ca_key_path] -ca_crt [ca_crt_path] -key [server_key_path] -crt [server_crt_path] -csr [server_csr_path] -cnf [openssl_cnf_path] -out [output_directory]
# Default output directory is ../certs if not provided as an argument.


SCRIPT_FILE=$(realpath "$0")




SCRIPT_DIR=$(realpath "$(dirname "$SCRIPT_FILE")")

OPENSSL_CNF="$SCRIPT_DIR/openssl.cnf"
if [ ! -f "$OPENSSL_CNF" ]; then
    echo "Error: openssl.cnf not found in the script directory."
    exit 1
fi

SERVER_NAME=${1:-"server"}
OUT_DIR="$SCRIPT_DIR/../certs/server"
CA_KEY="$SCRIPT_DIR/../certs/ca/ca.key"
CA_CRT="$SCRIPT_DIR/../certs/ca/ca.crt"

SERVER_KEY="$OUT_DIR/${SERVER_NAME}.key"
SERVER_CRT="$OUT_DIR/${SERVER_NAME}.crt"
SERVER_CSR="$OUT_DIR/${SERVER_NAME}.csr"
CREATE_KEY=true
CREATE_CRT=true

while [[ $# -gt 0 ]]; do
    case "$1" in
    -name)
        SERVER_NAME="$2"
        shift 2
        ;;
    -ca_key)
        CA_KEY="$2"
        shift 2
        ;;
    -ca_crt)
        CA_CRT="$2"
        shift 2
        ;;
    -out)
        OUT_DIR="$2"
        mkdir -p "$OUT_DIR"
        OUT_DIR=$(realpath "$OUT_DIR")
        shift 2
        ;;
    -key)
        SERVER_KEY="$2"
        shift 2
        ;;
    -crt)
        SERVER_CRT="$2"
        shift 2
        ;;
    -csr)
        SERVER_CSR="$2"
        shift 2
        ;;
    -cnf)
        OPENSSL_CNF="$2"
        if [ ! -f "$OPENSSL_CNF" ]; then
            echo "Error: openssl.cnf not found at $OPENSSL_CNF"
            exit 1
        fi
        shift 2
        ;;
    *)
        echo "Unknown option: $1"
        exit 1
        ;;
    esac
done


mkdir -p "$OUT_DIR"
OUT_DIR=$(realpath "$OUT_DIR")
OUT_DIR="$OUT_DIR/${SERVER_NAME}"
mkdir -p "$OUT_DIR"
SERVER_KEY="$OUT_DIR/${SERVER_NAME}.key"
SERVER_CRT="$OUT_DIR/${SERVER_NAME}.crt"
SERVER_CSR="$OUT_DIR/${SERVER_NAME}.csr"

# Check if CA key and certificate exist
if [ ! -f "$CA_KEY" ]; then
    echo "Error: CA key not found at $CA_KEY"
    exit 1
fi
if [ ! -f "$CA_CRT" ]; then
    echo "Error: CA certificate not found at $CA_CRT"
    exit 1
fi

if [ -f "$SERVER_KEY" ]; then
    echo "Warning: Server key already exists at $SERVER_KEY. Are you sure you want to overwrite it? (y/n)"
    read -r confirm
    if [[ "$confirm" != "y" && "$confirm" != "Y" ]]; then
        CREATE_KEY=false
        echo "Skipping server key generation."
    fi
fi

if [ -f "$SERVER_CRT" ]; then
    echo "Warning: Server certificate already exists at $SERVER_CRT. Are you sure you want to overwrite it? (y/n)"
    read -r confirm
    if [[ "$confirm" != "y" && "$confirm" != "Y" ]]; then
        CREATE_CRT=false
        echo "Skipping server certificate generation."
    fi
fi
if [ "$CREATE_KEY" = false ] && [ "$CREATE_CRT" = false ]; then
    echo "No changes made. Exiting."
    exit 0
fi


if [ "$CREATE_KEY" = true ]; then
    echo "Generating server private key in $OUT_DIR"
    openssl genrsa -out "$OUT_DIR/server.key" 4096
fi

if [ "$CREATE_CRT" = true ]; then
    echo "Generating server certificate in $OUT_DIR"
    openssl req -new -key "$OUT_DIR/server.key" -out "$OUT_DIR/server.csr" -config "$OPENSSL_CNF"
    openssl x509 -req -in "$OUT_DIR/server.csr" -CA "$CA_CRT" -CAkey "$CA_KEY" -CAcreateserial -out "$OUT_DIR/server.crt" -days 3650 -sha256 -extfile "$OPENSSL_CNF" -extensions v3_req
fi

echo "Server certificate and key generated successfully in $OUT_DIR"
echo "Server private key: $OUT_DIR/server.key"
echo "Server certificate: $OUT_DIR/server.crt"
echo "Server CSR: $OUT_DIR/server.csr"