#!/usr/bin/env bash
############################################################
# Created by: Guy Shaked                                   #
# Github: https://github.com/shakedguy                     #
# Phone: +972542422521                                     #
############################################################
#
# Generate client private key, certificate signing request (CSR) and self-signed certificate using openssl.cnf configuration file.
# and sign it with the CA certificate.
# Usage: ./gen-client-cert [name] [output_directory] -ca_key [ca_key_path] -ca_crt [ca_crt_path] -key [client_key_path] -crt [client_crt_path] -csr [client_csr_path] -cnf [openssl_cnf_path] -out [output_directory] -name [client_name]
# Default output directory is ../certs if not provided as an argument.



SCRIPT_FILE=$(realpath "$0")
SCRIPT_DIR=$(dirname "$SCRIPT_FILE")
CLIENT_CNF="$SCRIPT_DIR/client.cnf"
if [ ! -f "$CLIENT_CNF" ]; then
    echo "Error: client.cnf not found in the script directory."
    exit 1
fi

CLIENT_NAME=${1:-"client"}
OUT_DIR="$SCRIPT_DIR/../certs/client"
CA_KEY="$SCRIPT_DIR/../certs/ca/ca.key"
CA_CRT="$SCRIPT_DIR/../certs/ca/ca.crt"

CLIENT_KEY="$OUT_DIR/${CLIENT_NAME}.key"
CLIENT_CRT="$OUT_DIR/${CLIENT_NAME}.crt"
CLIENT_CSR="$OUT_DIR/${CLIENT_NAME}.csr"
CREATE_KEY=true
CREATE_CRT=true
while [[ $# -gt 0 ]]; do
    case "$1" in
    -name)
        CLIENT_NAME="$2"
        shift 2
        ;;
    -ca_key)
        CA_KEY="$2"
        shift 2
        ;;
    -ca_crt)
        CA_CRT="$2"
        shift 2
        ;;
    -out)
        OUT_DIR="$2"
        mkdir -p "$OUT_DIR"
        OUT_DIR=$(realpath "$OUT_DIR")
        shift 2
        ;;
    -key)
        CLIENT_KEY="$2"
        shift 2
        ;;
    -crt)
        CLIENT_CRT="$2"
        shift 2
        ;;
    -csr)
        CLIENT_CSR="$2"
        shift 2
        ;;
    -cnf)
        CLIENT_CNF="$2"
        if [ ! -f "$CLIENT_CNF" ]; then
            echo "Error: openssl.cnf not found at $CLIENT_CNF"
            exit 1
        fi
        shift 2
        ;;
    *)
        echo "Unknown option: $1"
        exit 1
        ;;
    esac
done

# Check if CA key and certificate exist
if [ ! -f "$CA_KEY" ]; then
    echo "Error: CA key not found at $CA_KEY"
    exit 1
fi

if [ ! -f "$CA_CRT" ]; then
    echo "Error: CA certificate not found at $CA_CRT"
    exit 1
fi




mkdir -p "$OUT_DIR"
OUT_DIR=$(realpath "$OUT_DIR")
OUT_DIR="$OUT_DIR/${CLIENT_NAME}"
mkdir -p "$OUT_DIR"
CLIENT_KEY="$OUT_DIR/${CLIENT_NAME}.key"
CLIENT_CRT="$OUT_DIR/${CLIENT_NAME}.crt"
CLIENT_CSR="$OUT_DIR/${CLIENT_NAME}.csr"
if [ -f "$CLIENT_KEY" ]; then
    echo "Warning: Client key already exists at $CLIENT_KEY. Are you sure you want to overwrite it? (y/n)"
    read -r confirm
    if [[ "$confirm" != "y" && "$confirm" != "Y" ]]; then
        CREATE_KEY=false
        echo "Skipping client key generation."
    fi
fi
if [ -f "$CLIENT_CRT" ]; then
    echo "Warning: Client certificate already exists at $CLIENT_CRT. Are you sure you want to overwrite it? (y/n)"
    read -r confirm
    if [[ "$confirm" != "y" && "$confirm" != "Y" ]]; then
        CREATE_CRT=false
        echo "Skipping client certificate generation."
    fi
fi


if [ "$CREATE_KEY" = false ] && [ "$CREATE_CRT" = false ]; then
    echo "No changes made. Exiting."
    exit 0
fi
if [ "$CREATE_KEY" = true ]; then
    echo "Generating client private key at $CLIENT_KEY"
    openssl genrsa -out "$CLIENT_KEY" 4096
fi

if [ "$CREATE_CRT" = true ]; then
    echo "Generating client certificate signing request (CSR) at $CLIENT_CSR"
    openssl req -new -key "$CLIENT_KEY" -out "$CLIENT_CSR" -config "$CLIENT_CNF"
    
    echo "Signing client certificate with CA certificate at $CLIENT_CRT"
    openssl x509 -req -in "$CLIENT_CSR" -CA "$CA_CRT" -CAkey "$CA_KEY" -CAcreateserial -out "$CLIENT_CRT" -days 3650 -sha256 -extfile "$CLIENT_CNF" -extensions v3_req
fi
echo "Client certificate and key generated successfully in $OUT_DIR"
echo "Client private key: $CLIENT_KEY"
echo "Client certificate: $CLIENT_CRT"
echo "Client CSR: $CLIENT_CSR"