#!/usr/bin/env bash
############################################################
# Created by: Guy Shaked                                   #
# Github: https://github.com/shakedguy                     #
# Phone: +972542422521                                     #
############################################################
#
# Generate a self-signed CA certificate and private key using openssl.cnf configuration file.
# Usage: ./genca.sh [output_directory]
# Default output directory is ../certs if not provided as an argument.
# Ensure the output directory exists

set -e
set -o pipefail

SCRIPT_FILE=$(realpath "$0")
SCRIPT_DIR=$(dirname "$SCRIPT_FILE")
OPENSSL_CNF="$SCRIPT_DIR/openssl.cnf"
if [ ! -f "$OPENSSL_CNF" ]; then
    echo "Error: openssl.cnf not found in the script directory."
    exit 1
fi

OUT_DIR=${1:-"$SCRIPT_DIR/../certs"}

CREATE_KEY=true
CREATE_CRT=true

while [[ $# -gt 0 ]]; do
    case "$1" in
    -key)
        CA_KEY="$2"
        shift 2
        ;;
    -crt)
        CA_CRT="$2"
        shift 2
        ;;
    -cnf)
        OPENSSL_CNF="$2"
        if [ ! -f "$OPENSSL_CNF" ]; then
            echo "Error: openssl.cnf not found at $OPENSSL_CNF"
            exit 1
        fi
        shift 2
        ;;
    -out)
        OUT_DIR="$2"
        shift 2
        ;;
    *)
        echo "Unknown option: $1"
        exit 1
        ;;
    esac
done

mkdir -p "$OUT_DIR"
OUT_DIR=$(realpath "$OUT_DIR")
OUT_DIR="$OUT_DIR/ca"
mkdir -p "$OUT_DIR"
CA_KEY="$OUT_DIR/ca.key"
CA_CRT="$OUT_DIR/ca.crt"
if [ -f "$CA_KEY" ]; then
    echo "Warning: CA key already exists at $CA_KEY. Are you sure you want to overwrite it? (y/n)"
    read -r confirm
    if [[ "$confirm" != "y" && "$confirm" != "Y" ]]; then
        CREATE_KEY=false
        echo "Skipping CA key generation."
    fi
fi
if [ -f "$CA_CRT" ]; then
    echo "Warning: CA certificate already exists at $CA_CRT. Are you sure you want to overwrite it? (y/n)"
    read -r confirm
    if [[ "$confirm" != "y" && "$confirm" != "Y" ]]; then
        CREATE_CRT=false
        echo "Skipping CA certificate generation."
    fi
fi

if [ "$CREATE_KEY" = false ] && [ "$CREATE_CRT" = false ]; then
    echo "No changes made. Exiting."
    exit 0
fi
if [ "$CREATE_KEY" = true ]; then
    echo "Generating CA private key and certificate in $OUT_DIR"
    openssl genrsa -out "$CA_KEY" 4096
fi

if [ "$CREATE_CRT" = true ]; then
    echo "Generating CA certificate in $OUT_DIR"
    openssl req -x509 -new -nodes -key "$CA_KEY" -sha256 -days 3650 -out "$CA_CRT" -config "$OPENSSL_CNF"
fi

echo "CA private key and certificate generated successfully in $OUT_DIR"
echo "CA private key: $CA_KEY"
echo "CA certificate: $CA_CRT"
echo "CA certificate is valid for 10 years (3650 days)"
echo "You can use this CA certificate to sign server and client certificates."
echo "To generate server or client certificates, use the gen-server-cert or gen-client-cert scripts respectively."