#!/usr/bin/env bash
############################################################
# Created by: Guy Shaked                                   #
# Github: https://github.com/shakedguy                     #
# Phone: +972542422521                                     #
############################################################

set -e
set -o pipefail

epoch=$(date +%s)

echo $epoch
