/*
* This file was generated by a tool.
* Rerun sql-ts to regenerate this file.
*/
export type DrizzleMigration = {
  createdAt?: string | null;
  hash: string;
  id?: string;
}
export type Account = {
  accessToken?: string | null;
  accessTokenExpiresAt?: Date | null;
  accountId: string;
  createdAt?: Date;
  id: string;
  idToken?: string | null;
  password?: string | null;
  providerId: string;
  refreshToken?: string | null;
  refreshTokenExpiresAt?: Date | null;
  scope?: string | null;
  updatedAt?: Date;
  userId: string;
}
export type AuditLog = {
  action: string;
  actorId?: string | null;
  actorType: string;
  createdAt?: Date;
  entityId?: string | null;
  entityType: string;
  id: string;
  metadata?: string | null;
  payload?: string | null;
  source: string;
  teamSlug: string;
}
export type EventRule = {
  createdAt?: Date;
  description?: string | null;
  editAccess?: string;
  enabled?: any;
  errorMessage: string;
  eventId: string;
  id: string;
  name: string;
  query?: string | null;
  updatedAt?: Date;
}
export type Event = {
  createdById?: string | null;
  editAccess?: string;
  eventSchema?: string;
  icon: string;
  id: string;
  label: string;
  teamId: string;
  type: string;
  updatedAt?: Date;
}
export type Invitation = {
  createdAt?: Date;
  email: string;
  expiresAt: Date;
  id: string;
  inviterId: string;
  organizationId: string;
  role?: string | null;
  status?: string;
  teamId?: string | null;
}
export type Member = {
  createdAt?: Date;
  id: string;
  organizationId: string;
  role?: string;
  userId: string;
}
export type Organization = {
  createdAt?: Date;
  id: string;
  logo?: string | null;
  metadata?: string | null;
  name: string;
  slug: string;
}
export type RewardRule = {
  column?: string | null;
  createdAt?: Date;
  description?: string | null;
  editAccess?: string;
  enabled?: any;
  errorMessage: string;
  eventId: string;
  id: string;
  name: string;
  queries?: string | null;
  tab?: string | null;
  updatedAt?: Date;
}
export type Session = {
  activeOrganizationId?: string | null;
  activeTeamId?: string | null;
  createdAt?: Date;
  expiresAt: Date;
  id: string;
  impersonatedBy?: string | null;
  ipAddress?: string | null;
  token: string;
  updatedAt?: Date;
  userAgent?: string | null;
  userId: string;
}
export type TeamMember = {
  createdAt?: Date;
  id: string;
  role?: string;
  teamId: string;
  userId: string;
}
export type Team = {
  createdAt?: Date;
  id: string;
  name: string;
  organizationId: string;
  slug: string;
  updatedAt?: Date;
}
export type User = {
  banExpires?: Date | null;
  banReason?: string | null;
  banned?: any | null;
  createdAt?: Date;
  email: string;
  emailVerified?: any;
  id: string;
  image?: string | null;
  name: string;
  role?: string | null;
  updatedAt?: Date;
}
export type Verification = {
  createdAt?: Date;
  expiresAt: Date;
  id: string;
  identifier: string;
  updatedAt?: Date;
  value: string;
}
