#!/usr/bin/env bash
############################################################
# Created by: Guy Shaked                                   #
# Github: https://github.com/shakedguy                     #
# Phone: +972542422521                                     #
############################################################

set -e
set -o pipefail

timestamp=$(date +%s)
random_hex=$(openssl rand -hex 8 | tr '[:lower:]' '[:upper:]')
echo "${timestamp}-${random_hex}"
