#!/usr/bin/env python3
############################################################
# Created by: Guy Shaked                                   #
# Github: https://github.com/shakedguy                     #
# Phone: +972542422521                                     #
############################################################

from uuid import uuid7

print(uuid7())
