name: mysql
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: masterkey
      MYSQL_USER: mysql
      MYSQL_PASSWORD: masterkey
      MYSQL_DATABASE: backend
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    expose:
      - 3306
    ports:
      - 3306:3306
    volumes:
      - ../volumes/mysql/db/data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 20s
      timeout: 10s
      retries: 10

