services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: very-strong-password
      MYSQL_DATABASE: mysql
      MYSQL_USER: mysql
      MYSQL_PASSWORD: very-strong-password
    expose:
      - 3306
    ports:
      - 3306:3306
    volumes:
      - ../volumes/mysql/db/data:/var/lib/mysql
    healthcheck:
      test:
        ['CMD', 'mysqladmin', 'ping', '-u', 'root', '-pvery-strong-password']
      interval: 30s
      timeout: 10s
      retries: 5
