// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using tests.Data;

#nullable disable

namespace tests.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250918091855_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("tests.Model.MTX_TournamentV2SegmentData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Actions")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<string>("BracketRewards")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<string>("BracketVisuals")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<string>("Globals")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<string>("Visuals")
                        .IsRequired()
                        .HasColumnType("json");

                    b.HasKey("Id");

                    b.ToTable("mtx_tournament_v2_segment_data");
                });
#pragma warning restore 612, 618
        }
    }
}
