services:
  mongo:
    image: mongodb/mongodb-community-server:latest
    container_name: mongo
    restart: unless-stopped
    expose:
      - 27017
    ports:
      - 27017:27017
    volumes:
      - ../volumes/mongodb/db/data:/data/db
#262391116251
