
services:
  redis:
    image: redis:latest
    container_name: redis
    # command: dragonfly --logtostderr --cluster_mode=emulated --lock_on_hashtags
    restart: unless-stopped
    ulimits:
      memlock: -1
    expose:
      - 6379
    ports:
      - 6379:6379
    volumes:
      - ../volumes/redis/db/data:/data